@startuml

left to right direction
:Admin Bruker: as Admin
:Normal Bruker: as Bruker

Admin --> (administrere brukere)
(administrere brukere) --> (brukerlog)
(administrere brukere) --> (tilkoblede enheter)

Admin --> (betalings tjeneste)
(betalings tjeneste) --> (ordre liste)


Admin --> (Logg inn)
Bruker --> (Logg inn)

(Forside innhold) --> (Avspilling av videofremvisning)
Bruker --> (Forside innhold)
Bruker --> (søk / filter)
Bruker --> (Rediger profil)
(Rediger profil) --> (legg til bruker)
(Rediger profil) --> (slett en bruker)
(Rediger profil) --> (profil redigering)
(søk / filter) --> (Serie / film)
(Avspilling av videofremvisning) --> (Serie / film)

Bruker --> (Betaling av abonnoment)
(Betaling av abonnoment) --> (vipps)
(Betaling av abonnoment) --> (visa)
(Betaling av abonnoment) --> (mastercard)


@enduml